# Generated by Django 4.1.1 on 2023-04-23 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(default='someone@gmail.com', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='someone@gmail.com', max_length=254)),
                ('name', models.CharField(max_length=30, null=True)),
                ('feedback', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('foodpic', models.ImageField(blank=True, null=True, upload_to='uploads/Food_Items')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('nv', models.TextField(choices=[('1', 'Veg'), ('2', 'NonVeg'), ('3', 'Both')], default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('name', models.CharField(max_length=30, null=True)),
                ('role', models.TextField(choices=[('1', 'Customer'), ('2', 'Restaurant')], default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', phone_field.models.PhoneField(max_length=31, null=True)),
                ('email', models.EmailField(default='someone@gmail.com', max_length=254, unique=True)),
                ('street', models.CharField(blank=True, max_length=70, null=True)),
                ('area', models.CharField(blank=True, max_length=70, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='menuitem', to='Client.menuitem')),
            ],
        ),
    ]
