# Generated by Django 4.1.1 on 2023-04-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
