# Generated by Django 4.1.1 on 2023-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_menuitem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
