# Generated by Django 4.1.1 on 2023-04-29 00:25

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='allergy',
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Customer_pics'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='someone@gmail.com', max_length=254, null=True, unique=True),
        ),
    ]
