# Generated by Django 4.1.1 on 2023-04-28 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0004_alter_menuitem_available_alter_order_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('aadhar', models.IntegerField(null=True, unique=True)),
                ('previous_workplace', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', phone_field.models.PhoneField(max_length=31, null=True, unique=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads/Agent_pics')),
                ('phone', phone_field.models.PhoneField(max_length=31, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('vehile_license', models.CharField(max_length=30, null=True)),
                ('rate', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(null=True)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryPartner.agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.profile')),
                ('delagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryPartner.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='rev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentrev', to='DeliveryPartner.agentreview'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
