# Generated by Django 4.1.1 on 2023-04-23 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=70, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads/Restaurant_pics')),
                ('phone', phone_field.models.PhoneField(max_length=31, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('cuisine', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.TextField(null=True)),
                ('nv', models.TextField(choices=[('1', 'Veg'), ('2', 'NonVeg'), ('3', 'Both')], default='1')),
                ('rate', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(null=True)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev', to='Restaurant.restaurantreview'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.profile')),
                ('rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
            ],
        ),
    ]
